# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		           "sloev / Johannes Valbjørn"
description:	       "sloev / Johannes Valbjørn portfolio"
author:              "Sloev / Johannes Valbjørn"
