#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio of sloev / Johannes Valbjørn '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'sloevgithub'

#-------------------------------
# About Section

about: >
 # About

  This is the personal portfolio of *sloev* (Johannes Valbjørn)
  
  Sloev is a vj, tinkerer, documentarist and allround audio visual artist.
  
  Johannes Valbjørn is a dad to three, bikerider, opensource pythonista and allround agile software developer.
  
  Together they form a unity of intuitive chaos that delivers on time.


  All projects and sourcecode are MIT licensed unless specified otherwise.


  The site is built using [LeNPaul's portfolio template](https://github.com/LeNPaul/portfolio-jekyll-theme/fork).

contact: >
  # Contact

  You may contact me [through my email](mailto:johannes.valbjorn+sloevgithub@gmail.com) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Smells Like Sweat - doommetal documentary', folder: 'smells_like_sweat', file: 'projects/smells_like_sweat.html'}
- {name: 'kfa/sloev - markov fimbul performance', folder: 'kfa_sloev', file: 'projects/kfa_sloev.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/sloev'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/johannes-gårdsted-valbjørn-446654110'}
- {icon: 'envelope', link: 'mailto:johannes.valbjorn+sloevgithub@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
